services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - 5678:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=workflow.vinesma.duckdns.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://workflow.vinesma.duckdns.org/
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - DB_SQLITE_POOL_SIZE=4
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_PROXY_HOPS=1
    volumes:
      - /mnt/storage/SERVICES/n8n/data:/home/node/.n8n
      - /mnt/storage/SERVICES/n8n/files:/files
      - /mnt/storage/SERVICES/Syncthing/data:/server/notes
