services:
  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    ports:
      - 5678:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
      - NODE_ENV=production
      - WEBHOOK_URL=
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - DB_SQLITE_POOL_SIZE=4
    volumes:
      - ./data:/home/node/.n8n
      - ./data/files:/files
