services:
  file-browser:
    image: filebrowser/filebrowser
    ports:
      - 8686:80
    volumes:
      - /mnt/storage:/srv
      - /mnt/storage/SERVICES/FileBrowser/db:/database
      - /mnt/storage/SERVICES/FileBrowser/config:/config
    restart: no
