services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:stable
    user: 1000:1000
    environment:
      - TZ=America/Sao_Paulo
      - FLARESOLVERR_ENABLED=true
      - FLARESOLVERR_URL=http://flaresolverr:8191
    volumes:
      - /mnt/storage/SERVICES/Suwayomi/data:/home/suwayomi/.local/share/Tachidesk
    ports:
      - "4567:4567"
    restart: no

  flaresolverr:
    image: ghcr.io/thephaseless/byparr:latest
    container_name: flaresolverr
    environment:
      - TZ=America/Sao_Paulo
    restart: no